// Code generated by encore. DO NOT EDIT.

package quizzes

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	ListAdminQuizzes(ctx context.Context) (*QuizListResponse, error)

	CreateQuiz(ctx context.Context, p *UpsertQuizRequest) (*AdminQuizDetail, error)

	GetAdminQuiz(ctx context.Context, id int64) (*AdminQuizDetail, error)

	UpdateQuiz(ctx context.Context, id int64, p *UpsertQuizRequest) (*AdminQuizDetail, error)

	DeleteQuiz(ctx context.Context, id int64) (*DeleteResponse, error)

	PublishQuiz(ctx context.Context, id int64, p *PublishRequest) (*AdminQuizDetail, error)

	ListPublishedQuizzes(ctx context.Context) (*QuizListResponse, error)

	GetQuiz(ctx context.Context, id int64) (*PublicQuizDetail, error)
}
